[package]
name = "ciro-parser"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ciro-core.workspace = true
kdl.workspace = true
miette.workspace = true
thiserror.workspace = true

[lints]
workspace = true
