allow-indexing-slicing-in-tests = true
suppress-restriction-lint-in-const = true
allow-unwrap-in-consts = true
allow-unwrap-in-tests = true
allow-expect-in-consts = true
allow-expect-in-tests = true
allow-panic-in-tests = true